module.exports = {
    externals: {
        electron: 'commonjs electron',
        // Node.js built-in modules:
        assert: 'commonjs assert',
        async_hooks: 'commonjs async_hooks',
        buffer: 'commonjs buffer',
        child_process: 'commonjs child_process',
        cluster: 'commonjs cluster',
        console: 'commonjs console',
        constants: 'commonjs constants',
        crypto: 'commonjs crypto',
        dgram: 'commonjs dgram',
        dns: 'commonjs dns',
        domain: 'commonjs domain',
        events: 'commonjs events',
        fs: 'commonjs fs',
        http: 'commonjs http',
        http2: 'commonjs http2',
        https: 'commonjs https',
        inspector: 'commonjs inspector',
        module: 'commonjs module',
        net: 'commonjs net',
        os: 'commonjs os',
        path: 'commonjs path',
        perf_hooks: 'commonjs perf_hooks',
        process: 'commonjs process',
        punycode: 'commonjs punycode',
        querystring: 'commonjs querystring',
        readline: 'commonjs readline',
        repl: 'commonjs repl',
        stream: 'commonjs stream',
        string_decoder: 'commonjs string_decoder',
        timers: 'commonjs timers',
        tls: 'commonjs tls',
        trace_events: 'commonjs trace_events',
        tty: 'commonjs tty',
        url: 'commonjs url',
        util: 'commonjs util',
        v8: 'commonjs v8',
        vm: 'commonjs vm',
        wasi: 'commonjs wasi',
        worker_threads: 'commonjs worker_threads',
        zlib: 'commonjs zlib',
    },
};
